import React from 'react';
import { useTranslation } from 'react-i18next';

interface ReportFooterProps {
  organizationName?: string;
  systemName?: string;
  contactInfo?: string;
  disclaimer?: string;
  className?: string;
}

export const ReportFooter: React.FC<ReportFooterProps> = ({
  organizationName = 'WILL',
  systemName,
  contactInfo,
  disclaimer,
  className = '',
}) => {
  const { t, i18n } = useTranslation();
  const currentYear = new Date().getFullYear();
  
  const defaultSystemName = systemName || (t("reports.intelligentTrafficAnalysisSystem") || "Sistema de Análisis de Tráfico Inteligente");
  const defaultDisclaimer = disclaimer || (t("reports.autoGeneratedDisclaimer") || "Este reporte fue generado automáticamente por el sistema WILL");

  return (
    <footer className={`mt-auto pt-8 border-t-2 border-gray-300 ${className}`}>
      <div className="bg-gray-50 p-6 rounded-lg">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Organization Info */}
          <div>
            <h4 className="text-lg font-semibold text-gray-800 mb-2">{organizationName}</h4>
            <p className="text-sm text-gray-600 mb-2">{defaultSystemName}</p>
            {contactInfo && (
              <p className="text-sm text-gray-600">{contactInfo}</p>
            )}
          </div>
          
          {/* Report Info */}
          <div className="text-right">
            <div className="text-sm text-gray-600 space-y-1">
              <p>{t("reports.systemVersion") || "Versión del Sistema"}: v2.0.1</p>
              <p>{t("reports.reportFormat") || "Formato de Reporte"}: PDF</p>
              <p>{t("reports.generated") || "Generado"}: {new Date().toLocaleString(i18n.language === 'ko' ? 'ko-KR' : 'es-PE')}</p>
            </div>
          </div>
        </div>
        
        {/* Disclaimer and Copyright */}
        <div className="mt-6 pt-4 border-t border-gray-300">
          <div className="text-center text-gray-600 text-sm space-y-2">
            <p>© {currentYear} {organizationName} - {defaultSystemName}</p>
            <p>{defaultDisclaimer}</p>
            <p className="text-xs">
              {t("reports.dataDisclaimer") || "Los datos presentados en este reporte son generados automáticamente y reflejan las condiciones de tráfico en el momento de la consulta."}
            </p>
          </div>
        </div>
      </div>
      
      {/* Technical Footer */}
      <div className="mt-4 text-center text-xs text-gray-500">
        <p>
          {t("reports.technicalReportGenerated") || "Reporte técnico generado por el módulo de análisis de tráfico"} | 
          {t("reports.technicalSupport") || "Para soporte técnico contacte al administrador del sistema"}
        </p>
      </div>
    </footer>
  );
};