# Generated by Django 5.2.3 on 2025-06-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.IntegerField()),
                ('ticket_number', models.IntegerField()),
                ('incident_type', models.CharField(max_length=100)),
                ('incident_detail_type', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('managed_by', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('operator', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField()),
                ('last_status_update', models.DateTimeField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('intersection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.intersection')),
            ],
        ),
        migrations.CreateModel(
            name='TotalTrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('total_volume', models.IntegerField()),
                ('average_speed', models.FloatField()),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.intersection')),
            ],
            options={
                'db_table': 'total_traffic_volume',
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='total_traff_interse_875aef_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('direction', models.CharField(choices=[('NS', 'North to South'), ('SN', 'South to North'), ('EW', 'East to West'), ('WE', 'West to East')], max_length=2)),
                ('volume', models.IntegerField()),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_volumes', to='traffic.intersection')),
            ],
            options={
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='traffic_tra_interse_34ed1d_idx'), models.Index(fields=['direction'], name='traffic_tra_directi_cd0ba7_idx')],
            },
        ),
    ]
