# Generated by Django 5.2.5 on 2025-08-29 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(default='', max_length=100, verbose_name='Incident Type')),
                ('intersection_name', models.CharField(default='', max_length=200, verbose_name='Intersection Name')),
                ('district', models.CharField(default='', max_length=100, verbose_name='District')),
                ('managed_by', models.CharField(default='', max_length=100, verbose_name='Managed By')),
                ('assigned_to', models.CharField(default='', max_length=100, verbose_name='Assigned To')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('status', models.CharField(default='OPEN', max_length=50, verbose_name='Status')),
                ('user', models.CharField(default='', max_length=100, verbose_name='User')),
                ('equipment_locked', models.CharField(choices=[('S', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Equipment Locked')),
                ('last_status_update', models.DateTimeField(auto_now=True, verbose_name='Last Status Update')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('sii_id', models.IntegerField(blank=True, null=True, verbose_name='SII ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type', models.CharField(default='', max_length=100, verbose_name='Type')),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.intersection', verbose_name='Linked Intersection')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['incident_type'], name='traffic_inc_inciden_7cdb1e_idx'), models.Index(fields=['status'], name='traffic_inc_status_875367_idx'), models.Index(fields=['registered_at'], name='traffic_inc_registe_ea5b75_idx'), models.Index(fields=['district'], name='traffic_inc_distric_84da7e_idx'), models.Index(fields=['intersection'], name='traffic_inc_interse_ae5afd_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntersectionFavoriteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(verbose_name='즐겨찾기 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_logs', to='traffic.intersection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '교차로 즐겨찾기 로그',
                'verbose_name_plural': '교차로 즐겨찾기 로그들',
                'indexes': [models.Index(fields=['intersection', 'user', 'is_favorite'], name='traffic_int_interse_d77397_idx'), models.Index(fields=['user', 'is_favorite'], name='traffic_int_user_id_672cbd_idx'), models.Index(fields=['created_at'], name='traffic_int_created_71b3a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntersectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='즐겨찾기 수')),
                ('ai_report_count', models.PositiveIntegerField(default=0, verbose_name='AI 리포트 요청 수')),
                ('last_viewed', models.DateTimeField(blank=True, null=True, verbose_name='마지막 조회 시간')),
                ('last_ai_report', models.DateTimeField(blank=True, null=True, verbose_name='마지막 AI 리포트 요청 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='traffic.intersection')),
            ],
            options={
                'verbose_name': '교차로 통계',
                'verbose_name_plural': '교차로 통계들',
                'indexes': [models.Index(fields=['view_count'], name='traffic_int_view_co_49689e_idx'), models.Index(fields=['favorite_count'], name='traffic_int_favorit_8340eb_idx'), models.Index(fields=['last_viewed'], name='traffic_int_last_vi_201324_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntersectionViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='조회 시간')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='traffic.intersection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '교차로 조회 로그',
                'verbose_name_plural': '교차로 조회 로그들',
                'indexes': [models.Index(fields=['intersection', 'viewed_at'], name='traffic_int_interse_752252_idx'), models.Index(fields=['user', 'viewed_at'], name='traffic_int_user_id_5eed84_idx'), models.Index(fields=['ip_address'], name='traffic_int_ip_addr_154cc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='S_Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(default='', max_length=100, verbose_name='Incident Type')),
                ('intersection_name', models.CharField(default='', max_length=200, verbose_name='Intersection Name')),
                ('district', models.CharField(default='', max_length=100, verbose_name='District')),
                ('managed_by', models.CharField(default='', max_length=100, verbose_name='Managed By')),
                ('assigned_to', models.CharField(default='', max_length=100, verbose_name='Assigned To')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('status', models.CharField(default='OPEN', max_length=50, verbose_name='Status')),
                ('user', models.CharField(default='', max_length=100, verbose_name='User')),
                ('equipment_locked', models.CharField(choices=[('S', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Equipment Locked')),
                ('last_status_update', models.DateTimeField(auto_now=True, verbose_name='Last Status Update')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('sii_id', models.IntegerField(blank=True, null=True, verbose_name='SII ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type', models.CharField(default='', max_length=100, verbose_name='Type')),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_incidents', to='traffic.intersection', verbose_name='Linked Intersection')),
            ],
            options={
                'verbose_name': 'Secure Incident',
                'verbose_name_plural': 'Secure Incidents',
                'db_table': 'S_incident',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['incident_type'], name='S_incident_inciden_db5542_idx'), models.Index(fields=['status'], name='S_incident_status_57d7e5_idx'), models.Index(fields=['registered_at'], name='S_incident_registe_0067b8_idx'), models.Index(fields=['district'], name='S_incident_distric_31c4ec_idx'), models.Index(fields=['intersection'], name='S_incident_interse_8f0724_idx')],
            },
        ),
        migrations.CreateModel(
            name='S_TotalTrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('total_volume', models.IntegerField()),
                ('average_speed', models.FloatField()),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_total_traffic_volumes', to='traffic.intersection')),
            ],
            options={
                'db_table': 'S_total_traffic_volume',
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='S_total_tra_interse_64206b_idx')],
            },
        ),
        migrations.CreateModel(
            name='S_TrafficInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('interpretation_text', models.TextField()),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('peak_direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_interpretations', to='traffic.intersection')),
            ],
            options={
                'db_table': 'S_traffic_interpretation',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='S_traffic_i_interse_e57a82_idx'), models.Index(fields=['congestion_level'], name='S_traffic_i_congest_c52f7e_idx')],
                'unique_together': {('intersection', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='S_TrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1)),
                ('volume', models.IntegerField()),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_traffic_volumes', to='traffic.intersection')),
            ],
            options={
                'db_table': 'S_traffic_volume',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='S_traffic_v_interse_792653_idx'), models.Index(fields=['direction'], name='S_traffic_v_directi_5f639d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TotalTrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('total_volume', models.IntegerField()),
                ('average_speed', models.FloatField()),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.intersection')),
            ],
            options={
                'db_table': 'total_traffic_volume',
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='total_traff_interse_875aef_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('interpretation_text', models.TextField()),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('peak_direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='traffic.intersection')),
            ],
            options={
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='traffic_tra_interse_3f4b5f_idx'), models.Index(fields=['congestion_level'], name='traffic_tra_congest_2b3bde_idx')],
                'unique_together': {('intersection', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='TrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1)),
                ('volume', models.IntegerField()),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_volumes', to='traffic.intersection')),
            ],
            options={
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='traffic_tra_interse_34ed1d_idx'), models.Index(fields=['direction'], name='traffic_tra_directi_cd0ba7_idx')],
            },
        ),
    ]
