# Generated by Django 5.2.4 on 2025-07-04 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-fecha'], 'verbose_name': '사건', 'verbose_name_plural': '사건들'},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='day',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='description',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='district',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='id',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_detail_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_number',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='last_status_update',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='managed_by',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='month',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='registered_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='status',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='year',
        ),
        migrations.AddField(
            model_name='incident',
            name='administrado_por',
            field=models.CharField(default='', max_length=100, verbose_name='관리 주체'),
        ),
        migrations.AddField(
            model_name='incident',
            name='asignado_a',
            field=models.CharField(default='', max_length=100, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='incident',
            name='bloqueo_de_equipo',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1, verbose_name='장비 잠금'),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='incident',
            name='cruce',
            field=models.CharField(default='', max_length=200, verbose_name='교차로'),
        ),
        migrations.AddField(
            model_name='incident',
            name='dir_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소'),
        ),
        migrations.AddField(
            model_name='incident',
            name='distrito',
            field=models.CharField(default='', max_length=100, verbose_name='구역'),
        ),
        migrations.AddField(
            model_name='incident',
            name='estado',
            field=models.CharField(default='ABIERTO', max_length=50, verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='incident',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='발생 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='fecha_ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='마지막 업데이트'),
        ),
        migrations.AddField(
            model_name='incident',
            name='id_sii',
            field=models.IntegerField(blank=True, null=True, verbose_name='SII ID'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='incident',
            name='usuario',
            field=models.CharField(default='', max_length=100, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(default='', max_length=100, verbose_name='사건 유형'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='intersection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.intersection', verbose_name='연결된 교차로'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_type'], name='traffic_inc_inciden_7cdb1e_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['estado'], name='traffic_inc_estado_dfac86_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['fecha'], name='traffic_inc_fecha_f9a0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['distrito'], name='traffic_inc_distrit_0a8b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['intersection'], name='traffic_inc_interse_ae5afd_idx'),
        ),
    ]
