# Generated by Django 5.2.6 on 2025-10-10 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='traffic.proposalcomment', verbose_name='부모 댓글')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='traffic.policyproposal', verbose_name='정책제안')),
            ],
            options={
                'verbose_name': '정책제안 댓글',
                'verbose_name_plural': '정책제안 댓글들',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['proposal', 'created_at'], name='traffic_pro_proposa_8015b1_idx'), models.Index(fields=['author'], name='traffic_pro_author__125e5f_idx'), models.Index(fields=['parent_comment'], name='traffic_pro_parent__02645e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficFlowAnalysisFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_name', models.CharField(blank=True, max_length=200, verbose_name='즐겨찾기 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='마지막 접근 시간')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='접근 횟수')),
                ('end_intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_favorites_as_end', to='traffic.intersection', verbose_name='도착 교차로')),
                ('start_intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_favorites_as_start', to='traffic.intersection', verbose_name='시작 교차로')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '교통 흐름 분석 즐겨찾기',
                'verbose_name_plural': '교통 흐름 분석 즐겨찾기들',
                'indexes': [models.Index(fields=['user', 'created_at'], name='traffic_tra_user_id_26425c_idx'), models.Index(fields=['start_intersection', 'end_intersection'], name='traffic_tra_start_i_f99469_idx'), models.Index(fields=['access_count'], name='traffic_tra_access__10e176_idx'), models.Index(fields=['last_accessed'], name='traffic_tra_last_ac_e92465_idx')],
                'unique_together': {('user', 'start_intersection', 'end_intersection')},
            },
        ),
        migrations.CreateModel(
            name='TrafficFlowAnalysisStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_favorites', models.PositiveIntegerField(default=0, verbose_name='총 즐겨찾기 수')),
                ('total_accesses', models.PositiveIntegerField(default=0, verbose_name='총 접근 횟수')),
                ('unique_users', models.PositiveIntegerField(default=0, verbose_name='고유 사용자 수')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='마지막 접근 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('end_intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_stats_as_end', to='traffic.intersection', verbose_name='도착 교차로')),
                ('start_intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_stats_as_start', to='traffic.intersection', verbose_name='시작 교차로')),
            ],
            options={
                'verbose_name': '교통 흐름 분석 통계',
                'verbose_name_plural': '교통 흐름 분석 통계들',
                'indexes': [models.Index(fields=['total_favorites'], name='traffic_tra_total_f_947b8b_idx'), models.Index(fields=['total_accesses'], name='traffic_tra_total_a_2c8285_idx'), models.Index(fields=['unique_users'], name='traffic_tra_unique__6d0a55_idx'), models.Index(fields=['last_accessed'], name='traffic_tra_last_ac_6328c4_idx')],
                'unique_together': {('start_intersection', 'end_intersection')},
            },
        ),
    ]
