# Generated by Django 5.2.4 on 2025-07-04 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_alter_incident_options_remove_incident_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='traffic_inc_estado_dfac86_idx',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='traffic_inc_fecha_f9a0cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='traffic_inc_distrit_0a8b5b_idx',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='id_sii',
            new_name='sii_id',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='administrado_por',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='bloqueo_de_equipo',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='cruce',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='dir_ip',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='fecha_ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='usuario',
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.CharField(default='', max_length=100, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='incident',
            name='district',
            field=models.CharField(default='', max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='incident',
            name='equipment_locked',
            field=models.CharField(choices=[('S', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Equipment Locked'),
        ),
        migrations.AddField(
            model_name='incident',
            name='intersection_name',
            field=models.CharField(default='', max_length=200, verbose_name='Intersection Name'),
        ),
        migrations.AddField(
            model_name='incident',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_status_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Status Update'),
        ),
        migrations.AddField(
            model_name='incident',
            name='managed_by',
            field=models.CharField(default='', max_length=100, verbose_name='Managed By'),
        ),
        migrations.AddField(
            model_name='incident',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registered At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(default='OPEN', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.CharField(default='', max_length=100, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.CharField(default='', max_length=100, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(default='', max_length=100, verbose_name='Incident Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='intersection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.intersection', verbose_name='Linked Intersection'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='traffic_inc_status_875367_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['registered_at'], name='traffic_inc_registe_ea5b75_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['district'], name='traffic_inc_distric_84da7e_idx'),
        ),
    ]
