# Generated by Django 5.2.4 on 2025-07-22 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_alter_incident_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('interpretation_text', models.TextField()),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('peak_direction', models.CharField(choices=[('NS', 'North to South'), ('SN', 'South to North'), ('EW', 'East to West'), ('WE', 'West to East')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='traffic.intersection')),
            ],
            options={
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='traffic_tra_interse_3f4b5f_idx'), models.Index(fields=['congestion_level'], name='traffic_tra_congest_2b3bde_idx')],
                'unique_together': {('intersection', 'datetime')},
            },
        ),
    ]
