# Generated by Django 5.2.4 on 2025-07-24 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_trafficinterpretation'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(default='', max_length=100, verbose_name='Incident Type')),
                ('intersection_name', models.CharField(default='', max_length=200, verbose_name='Intersection Name')),
                ('district', models.CharField(default='', max_length=100, verbose_name='District')),
                ('managed_by', models.CharField(default='', max_length=100, verbose_name='Managed By')),
                ('assigned_to', models.CharField(default='', max_length=100, verbose_name='Assigned To')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('status', models.CharField(default='OPEN', max_length=50, verbose_name='Status')),
                ('user', models.CharField(default='', max_length=100, verbose_name='User')),
                ('equipment_locked', models.CharField(choices=[('S', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Equipment Locked')),
                ('last_status_update', models.DateTimeField(auto_now=True, verbose_name='Last Status Update')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('sii_id', models.IntegerField(blank=True, null=True, verbose_name='SII ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type', models.CharField(default='', max_length=100, verbose_name='Type')),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_incidents', to='traffic.intersection', verbose_name='Linked Intersection')),
            ],
            options={
                'verbose_name': 'Secure Incident',
                'verbose_name_plural': 'Secure Incidents',
                'db_table': 'S_incident',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['incident_type'], name='S_incident_inciden_db5542_idx'), models.Index(fields=['status'], name='S_incident_status_57d7e5_idx'), models.Index(fields=['registered_at'], name='S_incident_registe_0067b8_idx'), models.Index(fields=['district'], name='S_incident_distric_31c4ec_idx'), models.Index(fields=['intersection'], name='S_incident_interse_8f0724_idx')],
            },
        ),
        migrations.CreateModel(
            name='S_TotalTrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('total_volume', models.IntegerField()),
                ('average_speed', models.FloatField()),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_total_traffic_volumes', to='traffic.intersection')),
            ],
            options={
                'db_table': 'S_total_traffic_volume',
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='S_total_tra_interse_64206b_idx')],
            },
        ),
        migrations.CreateModel(
            name='S_TrafficInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('interpretation_text', models.TextField()),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('peak_direction', models.CharField(choices=[('NS', 'North to South'), ('SN', 'South to North'), ('EW', 'East to West'), ('WE', 'West to East')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_interpretations', to='traffic.intersection')),
            ],
            options={
                'db_table': 'S_traffic_interpretation',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='S_traffic_i_interse_e57a82_idx'), models.Index(fields=['congestion_level'], name='S_traffic_i_congest_c52f7e_idx')],
                'unique_together': {('intersection', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='S_TrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('direction', models.CharField(choices=[('NS', 'North to South'), ('SN', 'South to North'), ('EW', 'East to West'), ('WE', 'West to East')], max_length=2)),
                ('volume', models.IntegerField()),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_traffic_volumes', to='traffic.intersection')),
            ],
            options={
                'db_table': 'S_traffic_volume',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='S_traffic_v_interse_792653_idx'), models.Index(fields=['direction'], name='S_traffic_v_directi_5f639d_idx')],
            },
        ),
    ]
