# Generated by Django 5.2.4 on 2025-07-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_s_incident_s_totaltrafficvolume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_trafficinterpretation',
            name='peak_direction',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1),
        ),
        migrations.AlterField(
            model_name='s_trafficvolume',
            name='direction',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1),
        ),
        migrations.AlterField(
            model_name='trafficinterpretation',
            name='peak_direction',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1),
        ),
        migrations.AlterField(
            model_name='trafficvolume',
            name='direction',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1),
        ),
    ]
