# Generated by Django 5.2.5 on 2025-08-29 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_alter_s_trafficinterpretation_peak_direction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionFavoriteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(verbose_name='즐겨찾기 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_logs', to='traffic.intersection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '교차로 즐겨찾기 로그',
                'verbose_name_plural': '교차로 즐겨찾기 로그들',
                'indexes': [models.Index(fields=['intersection', 'user', 'is_favorite'], name='traffic_int_interse_d77397_idx'), models.Index(fields=['user', 'is_favorite'], name='traffic_int_user_id_672cbd_idx'), models.Index(fields=['created_at'], name='traffic_int_created_71b3a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntersectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='즐겨찾기 수')),
                ('last_viewed', models.DateTimeField(blank=True, null=True, verbose_name='마지막 조회 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='traffic.intersection')),
            ],
            options={
                'verbose_name': '교차로 통계',
                'verbose_name_plural': '교차로 통계들',
                'indexes': [models.Index(fields=['view_count'], name='traffic_int_view_co_49689e_idx'), models.Index(fields=['favorite_count'], name='traffic_int_favorit_8340eb_idx'), models.Index(fields=['last_viewed'], name='traffic_int_last_vi_201324_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntersectionViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='조회 시간')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='traffic.intersection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '교차로 조회 로그',
                'verbose_name_plural': '교차로 조회 로그들',
                'indexes': [models.Index(fields=['intersection', 'viewed_at'], name='traffic_int_interse_752252_idx'), models.Index(fields=['user', 'viewed_at'], name='traffic_int_user_id_5eed84_idx'), models.Index(fields=['ip_address'], name='traffic_int_ip_addr_154cc7_idx')],
            },
        ),
    ]
