# Generated by Django 5.2.5 on 2025-08-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_intersectionfavoritelog_intersectionstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersectionstats',
            name='ai_report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='AI 리포트 요청 수'),
        ),
        migrations.AddField(
            model_name='intersectionstats',
            name='last_ai_report',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 AI 리포트 요청 시간'),
        ),
    ]
