# Generated by Django 5.2.3 on 2025-07-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincode',
            name='auto_generate',
            field=models.BooleanField(default=False, verbose_name='자동 생성 여부'),
        ),
        migrations.AddField(
            model_name='admincode',
            name='generation_interval_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='생성 간격 (시간)'),
        ),
        migrations.AddField(
            model_name='admincode',
            name='last_generated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 생성일'),
        ),
    ]
