# Generated by Django 5.2.3 on 2025-07-05 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_admincode_auto_generate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincode',
            options={'verbose_name': 'Admin Code', 'verbose_name_plural': 'Admin Codes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='admincode',
            name='auto_generate',
            field=models.BooleanField(default=False, verbose_name='Auto Generate'),
        ),
        migrations.AlterField(
            model_name='admincode',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Admin Code'),
        ),
        migrations.AlterField(
            model_name='admincode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='admincode',
            name='current_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Uses'),
        ),
        migrations.AlterField(
            model_name='admincode',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='admincode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='admincode',
            name='generation_interval_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Generation Interval (Hours)'),
        ),
        migrations.AlterField(
            model_name='admincode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='admincode',
            name='last_generated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Generated'),
        ),
        migrations.AlterField(
            model_name='admincode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, verbose_name='Max Uses'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_code_used',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Admin Code Used'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('admin', 'Administrator')], default='operator', max_length=10, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
