# Generated by Django 5.2.4 on 2025-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_admincode_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_salt',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
